######################################################################
# Automatically generated by qmake (3.0) Thu Sep 19 22:00:52 2013
######################################################################
QT += widgets

TEMPLATE = app
TARGET = tetris
INCLUDEPATH += .
QMAKE_CXX = clang++
QMAKE_CXXFLAGS = -std=c++11

# Input
SOURCES += main.cpp

HEADERS += \
    Bloque.h \
    Figura.h \
    Cola.h \
    Tablero.h \
    TableroView.h \
    GameController.h
